package com.lottery.model;
// Generated May 15, 2016 2:14:11 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Buyer generated by hbm2java
 */
@Entity
@Table(name = "buyer", catalog = "lottery", uniqueConstraints = @UniqueConstraint(columnNames = "ic")
)
public class Buyer implements java.io.Serializable {

    private long id;
    private String name;
    private String ic;
    private List<Ticket> tickets = new ArrayList<>();

    public Buyer() {
    }

    public Buyer(long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Buyer(long id, String name, String ic, List<Ticket> tickets) {
        this.id = id;
        this.name = name;
        this.ic = ic;
        this.tickets = tickets;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "ic", unique = true, length = 45)
    public String getIc() {
        return this.ic;
    }

    public void setIc(String ic) {
        this.ic = ic;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "buyer", cascade = CascadeType.ALL)
    public List<Ticket> getTickets() {
        return this.tickets;
    }

    public void setTickets(List<Ticket> tickets) {
        this.tickets = tickets;
    }

}
