package com.lottery.model;
// Generated May 10, 2016 4:58:03 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Buyer generated by hbm2java
 */
@Entity
@Table(name="buyer"
    ,catalog="lottery"
    , uniqueConstraints = @UniqueConstraint(columnNames="ic") 
)
public class Buyer  implements java.io.Serializable {


     private long id;
     private String name;
     private String ic;
     private Set tickets = new HashSet(0);

    public Buyer() {
    }

	
    public Buyer(long id, String name) {
        this.id = id;
        this.name = name;
    }
    public Buyer(long id, String name, String ic, Set tickets) {
       this.id = id;
       this.name = name;
       this.ic = ic;
       this.tickets = tickets;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="ic", unique=true, length=45)
    public String getIc() {
        return this.ic;
    }
    
    public void setIc(String ic) {
        this.ic = ic;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="buyer")
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }




}


