package com.lottery.model;
// Generated May 10, 2016 4:58:03 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DrawResult generated by hbm2java
 */
@Entity
@Table(name="draw_result"
    ,catalog="lottery"
    , uniqueConstraints = @UniqueConstraint(columnNames="draw_date") 
)
public class DrawResult  implements java.io.Serializable {


     private Long id;
     private Date drawDate;
     private String drawBalls;
     private String winBalls;
     private Set winTickets = new HashSet(0);

    public DrawResult() {
    }

	
    public DrawResult(Date drawDate, String drawBalls) {
        this.drawDate = drawDate;
        this.drawBalls = drawBalls;
    }
    public DrawResult(Date drawDate, String drawBalls, String winBalls, Set winTickets) {
       this.drawDate = drawDate;
       this.drawBalls = drawBalls;
       this.winBalls = winBalls;
       this.winTickets = winTickets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="draw_date", unique=true, nullable=false, length=10)
    public Date getDrawDate() {
        return this.drawDate;
    }
    
    public void setDrawDate(Date drawDate) {
        this.drawDate = drawDate;
    }
    
    @Column(name="draw_balls", nullable=false, length=250)
    public String getDrawBalls() {
        return this.drawBalls;
    }
    
    public void setDrawBalls(String drawBalls) {
        this.drawBalls = drawBalls;
    }
    
    @Column(name="win_balls", length=45)
    public String getWinBalls() {
        return this.winBalls;
    }
    
    public void setWinBalls(String winBalls) {
        this.winBalls = winBalls;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="drawResult")
    public Set getWinTickets() {
        return this.winTickets;
    }
    
    public void setWinTickets(Set winTickets) {
        this.winTickets = winTickets;
    }




}


