package com.lottery.model;
// Generated May 15, 2016 2:14:11 AM by Hibernate Tools 4.3.1

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TicketTable generated by hbm2java
 */
@Entity
@Table(name = "ticket_table", catalog = "lottery"
)
public class TicketTable implements java.io.Serializable {
    public static final byte FULL_LINE = 1;
    public static final byte FULL_TABLE = 2;

    private Long id;
    private Ticket ticket;
    private String firstLine;
    private String secondLine;
    private String thirdLine;
    private byte round;
    private String fullTable;
    private String blankIndices;
    private byte winType;
    private DrawResult drawResult;

    public TicketTable() {
    }

    public TicketTable(Ticket ticket, String firstLine, String secondLine, String thirdLine, byte round, String fullTable, String blankIndices, byte winType) {
        this.ticket = ticket;
        this.firstLine = firstLine;
        this.secondLine = secondLine;
        this.thirdLine = thirdLine;
        this.round = round;
        this.fullTable = fullTable;
        this.blankIndices = blankIndices;
        this.winType = winType;
    }

    public TicketTable(Ticket ticket, String firstLine, String secondLine, String thirdLine, byte round, String fullTable, String blankIndices, byte winType, DrawResult drawResult) {
        this.ticket = ticket;
        this.firstLine = firstLine;
        this.secondLine = secondLine;
        this.thirdLine = thirdLine;
        this.round = round;
        this.fullTable = fullTable;
        this.blankIndices = blankIndices;
        this.drawResult = drawResult;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ticket_id", nullable = false)
    public Ticket getTicket() {
        return this.ticket;
    }

    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }

    @Column(name = "first_line", nullable = false, length = 30)
    public String getFirstLine() {
        return this.firstLine;
    }

    public void setFirstLine(String firstLine) {
        this.firstLine = firstLine;
    }

    @Column(name = "second_line", nullable = false, length = 30)
    public String getSecondLine() {
        return this.secondLine;
    }

    public void setSecondLine(String secondLine) {
        this.secondLine = secondLine;
    }

    @Column(name = "third_line", nullable = false, length = 30)
    public String getThirdLine() {
        return this.thirdLine;
    }

    public void setThirdLine(String thirdLine) {
        this.thirdLine = thirdLine;
    }

    @Column(name = "round", nullable = false)
    public byte getRound() {
        return this.round;
    }

    public void setRound(byte round) {
        this.round = round;
    }

    @Column(name = "full_table", nullable = false, length = 90)
    public String getFullTable() {
        return this.fullTable;
    }

    public void setFullTable(String fullTable) {
        this.fullTable = fullTable;
    }

    @Column(name = "blank_indices", nullable = false, length = 15)
    public String getBlankIndices() {
        return this.blankIndices;
    }

    public void setBlankIndices(String blankIndices) {
        this.blankIndices = blankIndices;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "draw_result_id", nullable = true)
    public DrawResult getDrawResult() {
        return this.drawResult;
    }

    public void setDrawResult(DrawResult drawResult) {
        this.drawResult = drawResult;
    }

    @Column(name = "win_type", nullable = true)
    public byte getWinType() {
        return winType;
    }

    public void setWinType(byte winType) {
        this.winType = winType;
    }

    
    
    @Override
    public String toString() {
        return fullTable;
    }

}
