package com.lottery.model;
// Generated May 10, 2016 4:58:03 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name="ticket"
    ,catalog="lottery"
    , uniqueConstraints = @UniqueConstraint(columnNames="serial_number") 
)
public class Ticket  implements java.io.Serializable {


     private Long id;
     private Buyer buyer;
     private String serialNumber;
     private Date drawDate;
     private String firstLine;
     private String secondLine;
     private String thirdLine;
     private String fullTable;
     private String blankIndices;
     private byte round;
     private Set winTickets = new HashSet(0);

    public Ticket() {
    }

	
    public Ticket(Buyer buyer, String serialNumber, Date drawDate, String firstLine, String secondLine, String thirdLine, String fullTable, String blankIndices, byte round) {
        this.buyer = buyer;
        this.serialNumber = serialNumber;
        this.drawDate = drawDate;
        this.firstLine = firstLine;
        this.secondLine = secondLine;
        this.thirdLine = thirdLine;
        this.fullTable = fullTable;
        this.blankIndices = blankIndices;
        this.round = round;
    }
    public Ticket(Buyer buyer, String serialNumber, Date drawDate, String firstLine, String secondLine, String thirdLine, String fullTable, String blankIndices, byte round, Set winTickets) {
       this.buyer = buyer;
       this.serialNumber = serialNumber;
       this.drawDate = drawDate;
       this.firstLine = firstLine;
       this.secondLine = secondLine;
       this.thirdLine = thirdLine;
       this.fullTable = fullTable;
       this.blankIndices = blankIndices;
       this.round = round;
       this.winTickets = winTickets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="buyer_id", nullable=false)
    public Buyer getBuyer() {
        return this.buyer;
    }
    
    public void setBuyer(Buyer buyer) {
        this.buyer = buyer;
    }
    
    @Column(name="serial_number", unique=true, nullable=false, length=20)
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="draw_date", nullable=false, length=10)
    public Date getDrawDate() {
        return this.drawDate;
    }
    
    public void setDrawDate(Date drawDate) {
        this.drawDate = drawDate;
    }
    
    @Column(name="first_line", nullable=false, length=30)
    public String getFirstLine() {
        return this.firstLine;
    }
    
    public void setFirstLine(String firstLine) {
        this.firstLine = firstLine;
    }
    
    @Column(name="second_line", nullable=false, length=30)
    public String getSecondLine() {
        return this.secondLine;
    }
    
    public void setSecondLine(String secondLine) {
        this.secondLine = secondLine;
    }
    
    @Column(name="third_line", nullable=false, length=30)
    public String getThirdLine() {
        return this.thirdLine;
    }
    
    public void setThirdLine(String thirdLine) {
        this.thirdLine = thirdLine;
    }
    
    @Column(name="full_table", nullable=false, length=90)
    public String getFullTable() {
        return this.fullTable;
    }
    
    public void setFullTable(String fullTable) {
        this.fullTable = fullTable;
    }
    
    @Column(name="blank_indices", nullable=false, length=15)
    public String getBlankIndices() {
        return this.blankIndices;
    }
    
    public void setBlankIndices(String blankIndices) {
        this.blankIndices = blankIndices;
    }
    
    @Column(name="round", nullable=false)
    public byte getRound() {
        return this.round;
    }
    
    public void setRound(byte round) {
        this.round = round;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ticket")
    public Set getWinTickets() {
        return this.winTickets;
    }
    
    public void setWinTickets(Set winTickets) {
        this.winTickets = winTickets;
    }




}


