package com.lottery.model;
// Generated May 15, 2016 2:14:11 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "lottery", uniqueConstraints = @UniqueConstraint(columnNames = "serial_number")
)
public class Ticket implements java.io.Serializable {

    private Long id;
    private Buyer buyer;
    private String serialNumber;
    private Date drawDate;
    private List<TicketTable> ticketTables = new ArrayList<>();

    public Ticket() {
    }

    public Ticket(Buyer buyer, String serialNumber, Date drawDate) {
        this.buyer = buyer;
        this.serialNumber = serialNumber;
        this.drawDate = drawDate;
    }

    public Ticket(Buyer buyer, String serialNumber, Date drawDate, List<TicketTable> ticketTables) {
        this.buyer = buyer;
        this.serialNumber = serialNumber;
        this.drawDate = drawDate;
        this.ticketTables = ticketTables;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "buyer_id", nullable = false)
    public Buyer getBuyer() {
        return this.buyer;
    }

    public void setBuyer(Buyer buyer) {
        this.buyer = buyer;
    }

    @Column(name = "serial_number", unique = true, nullable = false, length = 20)
    public String getSerialNumber() {
        return this.serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "draw_date", nullable = false, length = 10)
    public Date getDrawDate() {
        return this.drawDate;
    }

    public void setDrawDate(Date drawDate) {
        this.drawDate = drawDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ticket", cascade = CascadeType.ALL)
    public List<TicketTable> getTicketTables() {
        return this.ticketTables;
    }

    public void setTicketTables(List<TicketTable> ticketTables) {
        this.ticketTables = ticketTables;
    }

}
