package com.lottery.model;
// Generated May 15, 2016 2:14:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WinTicket generated by hbm2java
 */
@Entity
@Table(name = "win_ticket", catalog = "lottery"
)
public class WinTicket implements java.io.Serializable {

    private Long id;
    private DrawResult drawResult;
    private TicketTable ticketTable;
    private Date drawDate;
    private String winType;

    public WinTicket() {
    }

    public WinTicket(DrawResult drawResult, TicketTable ticketTable, Date drawDate, String winType) {
        this.drawResult = drawResult;
        this.ticketTable = ticketTable;
        this.drawDate = drawDate;
        this.winType = winType;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "draw_result_id", nullable = false)
    public DrawResult getDrawResult() {
        return this.drawResult;
    }

    public void setDrawResult(DrawResult drawResult) {
        this.drawResult = drawResult;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ticket_table_id", nullable = false)
    public TicketTable getTicketTable() {
        return this.ticketTable;
    }

    public void setTicketTable(TicketTable ticketTable) {
        this.ticketTable = ticketTable;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "draw_date", nullable = false, length = 10)
    public Date getDrawDate() {
        return this.drawDate;
    }

    public void setDrawDate(Date drawDate) {
        this.drawDate = drawDate;
    }

    @Column(name = "win_type", nullable = false, length = 10)
    public String getWinType() {
        return this.winType;
    }

    public void setWinType(String winType) {
        this.winType = winType;
    }

}
